# Generated by Django 3.1.4 on 2021-01-01 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='code',
            field=models.CharField(default='gJTXyjGy', max_length=8, unique=True),
        ),
    ]
